##===- projects/hw1pass2/tools/hw1pass2/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=mlanalyzer

#
# List libraries that we'll need
# We use LIBS because hw1pass is a dynamic library.
#
USEDLIBS=mlanalyzer.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

